version: '3.8'

services:
  role:
    build:
      context: ./
      dockerfile: ./role.Dockerfile
    image: japhethlyh/rolems
    networks: [SBRP]
    restart: always
    ports:
    - "5002:5002"
  
  skill:
    build:
      context: ./
      dockerfile: ./skill.Dockerfile
    image: japhethlyh/skillms
    networks: [SBRP]
    restart: always
    ports: 
    - "5001:5001"

  staff:
    build:
      context: ./
      dockerfile: ./staff.Dockerfile
    image: japhethlyh/staffms
    networks: [SBRP]
    restart: always
    ports:
     - "5000:5000"

networks:
  SBRP: