name: Docker Compose Up

on:
  push:
    branches:
      - main  # Replace with your branch name
    pull_request:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # configure variables for running db script on aws
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your AWS region

      - name: Run SQL Script
          # Replace with the appropriate AWS RDS endpoint and credentials
        run: |
          aws rds-data execute-statement --resource-arn arn:aws:rds:us-east-1:123456789012:db:your-db-name --secret-arn arn:aws:secretsmanager:us-east-1:123456789012:secret:your-secret-name --sql "spm.sql"
        working-directory: ./db

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and start containers
        run: |
          docker-compose up -d
        working-directory: ./backend
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
      
      - name: Install dependencies
        run: pup install -r ./tests/requirements.txt

      - name: run role tests
        run: |
          test_role.py
        working-directory: ./tests

      - name: run skill tests
        run: |
          test_skill.py
        working-directory: ./tests

      - name: run staff tests
        run: |
          test_staff.py
        working-directory: ./tests

      - name: Stop and remove containers
        run: docker-compose down
        working-directory: ./backend
        
